// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Get these values from the Firebase console - 
  //    Project Overview > Apps Pill > Gears Icon
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'XXX',
    appId: 'XXX',
    messagingSenderId: 'XXX',
    projectId: 'XXX',
    authDomain: 'XXX',
    storageBucket: 'XXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'XXX',
    appId: 'XXX',
    messagingSenderId: 'XXX',
    projectId: 'XXX',
    storageBucket: 'XXX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'XXX',
    appId: 'XXX',
    messagingSenderId: 'XXX',
    projectId: 'XXX',
    storageBucket: 'XXX',
    iosClientId: 'XXX',
    iosBundleId: 'XXX',
  );
}
